// Database types for FreightView
// These would normally be auto-generated by Supabase CLI

// =====================
// ORGANIZATION TYPES (B2B Multi-tenant)
// =====================

export type OrganizationPlan = 'free' | 'starter' | 'professional' | 'enterprise';
export type UserRole = 'owner' | 'admin' | 'member' | 'viewer';

export interface Organization {
  id: string;
  name: string;
  slug: string;

  // Company details
  legal_name: string | null;
  tax_id: string | null;
  address: string | null;
  city: string | null;
  country_code: string | null;
  phone: string | null;
  website: string | null;
  logo_url: string | null;

  // Subscription
  plan: OrganizationPlan;
  plan_seats: number;
  plan_expires_at: string | null;

  // Settings
  default_currency: string;
  default_incoterms: string;
  fiscal_year_start: number;

  // Audit
  created_at: string;
  updated_at: string;
  created_by: string | null;
}

export interface OrganizationInvite {
  id: string;
  organization_id: string;
  email: string;
  role: UserRole;
  token: string;
  expires_at: string;
  invited_by: string | null;
  created_at: string;
  accepted_at: string | null;
}

export interface OrganizationForwarder {
  id: string;
  organization_id: string;
  forwarder_id: string;
  account_number: string | null;
  contact_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  is_preferred: boolean;
  contract_rate_available: boolean;
  contract_expires_at: string | null;
  notes: string | null;
  created_at: string;
  created_by: string | null;
  forwarder?: Forwarder;
}

export interface ActivityLog {
  id: string;
  organization_id: string;
  user_id: string | null;
  action: string;
  entity_type: string | null;
  entity_id: string | null;
  metadata: Record<string, unknown>;
  ip_address: string | null;
  user_agent: string | null;
  created_at: string;
}

// =====================
// REQUEST/QUOTE STATUS TYPES
// =====================

export type RequestStatus =
  | 'draft'
  | 'pending_quotes'
  | 'quotes_received'
  | 'decision_pending'
  | 'booked'
  | 'cancelled';

export type TransportMode = 'air' | 'sea';
export type ModePreference = 'air' | 'sea' | 'any';
export type QuoteStatus = 'active' | 'expired' | 'selected' | 'declined';
export type QuoteSource = 'manual' | 'email' | 'api';

export interface Profile {
  id: string;
  email: string;
  company_name: string | null;
  phone: string | null;
  default_incoterms: string;
  created_at: string;
  updated_at: string;

  // Organization-based auth (B2B)
  organization_id: string | null;
  role: UserRole | null;
  job_title: string | null;
  is_active: boolean;
  invited_by: string | null;
  invited_at: string | null;
  last_login_at: string | null;

  // Joined data
  organization?: Organization;
}

export interface Forwarder {
  id: string;
  name: string;
  short_code: string;
  logo_url: string | null;
  default_quote_email: string | null;
  api_enabled: boolean;
  created_at: string;
}

export interface UserForwarder {
  id: string;
  user_id: string;
  forwarder_id: string;
  contact_email: string | null;
  contact_name: string | null;
  notes: string | null;
  created_at: string;
  forwarder?: Forwarder;
}

export interface Country {
  code: string;
  name: string;
}

export interface Port {
  code: string;
  name: string;
  country_code: string;
  port_type: 'seaport' | 'airport' | 'inland';
  city: string;
}

export interface CargoType {
  code: string;
  name: string;
  requires_temp_control: boolean;
  is_hazmat: boolean;
}

export interface ShipmentRequest {
  id: string;
  user_id: string;
  organization_id: string | null; // B2B multi-tenant support
  reference: string | null;
  status: RequestStatus;

  // Origin
  origin_country: string | null;
  origin_city: string | null;
  origin_port: string | null;
  origin_address: string | null;

  // Destination
  dest_country: string | null;
  dest_city: string | null;
  dest_port: string | null;
  dest_address: string | null;

  // Cargo
  cargo_type: string | null;
  cargo_description: string | null;
  weight_kg: number | null;
  volume_cbm: number | null;
  pieces: number | null;
  value_usd: number | null;
  is_stackable: boolean;
  is_hazmat: boolean;
  temperature_required: string | null;

  // Requirements
  cargo_ready_date: string | null;
  delivery_required_date: string | null;
  mode_preference: ModePreference;
  incoterms: string;
  special_instructions: string | null;

  // Metadata
  created_at: string;
  updated_at: string;
  submitted_at: string | null;
}

export interface Quote {
  id: string;
  request_id: string;
  forwarder_id: string;
  mode: TransportMode;
  status: QuoteStatus;

  // Pricing
  currency: string;
  total_amount: number;
  freight_charge: number | null;
  fuel_surcharge: number | null;
  handling_charge: number | null;
  documentation_fee: number | null;
  terminal_handling: number | null;
  other_charges: number | null;

  // Rate details
  rate_basis: string | null;
  rate_per_unit: number | null;
  chargeable_weight: number | null;

  // Schedule
  etd: string | null;
  eta: string | null;
  transit_days: number | null;
  carrier: string | null;
  vessel_flight: string | null;
  routing: string | null;
  transshipment_ports: string[] | null;

  // Terms
  valid_until: string | null;
  free_days_origin: number;
  free_days_dest: number;
  payment_terms: string | null;

  // Source
  received_via: QuoteSource;
  raw_email_id: string | null;
  notes: string | null;

  created_at: string;
  updated_at: string;

  // Joined data
  forwarder?: Forwarder;
}

export interface Decision {
  id: string;
  request_id: string;
  selected_quote_id: string | null;
  best_air_quote_id: string | null;
  best_sea_quote_id: string | null;
  savings_amount: number | null;
  savings_percentage: number | null;
  decision_reason: string | null;
  decided_at: string;
  decided_by: string | null;
}

// API request/response types
export interface CreateRequestInput {
  reference?: string;
  origin_country: string;
  origin_city: string;
  dest_country: string;
  dest_city: string;
  cargo_type: string;
  weight_kg: number;
  volume_cbm: number;
  pieces?: number;
  value_usd?: number;
  cargo_ready_date: string;
  delivery_required_date: string;
  mode_preference: ModePreference;
  special_instructions?: string;
  forwarder_ids: string[];
}

export interface CreateQuoteInput {
  request_id: string;
  forwarder_id: string;
  mode: TransportMode;
  total_amount: number;
  freight_charge?: number;
  fuel_surcharge?: number;
  handling_charge?: number;
  documentation_fee?: number;
  terminal_handling?: number;
  etd: string;
  eta: string;
  transit_days: number;
  carrier?: string;
  routing?: string;
  valid_until: string;
}

// Enriched types with joins
export interface RequestWithQuotes extends ShipmentRequest {
  quotes: Quote[];
  request_forwarders: {
    forwarder_id: string;
    forwarder: Forwarder;
    email_sent_at: string | null;
  }[];
}

export interface QuoteComparison {
  request: ShipmentRequest;
  air_quotes: Quote[];
  sea_quotes: Quote[];
  best_air: Quote | null;
  best_sea: Quote | null;
  potential_savings: number | null;
  recommendation: 'air' | 'sea' | null;
  recommendation_reason: string | null;
}
